### ISSUE TITLE
Ubuntu 19.10 - android_build_env.sh

### ISSUE THREAD

**Issue by julian-fairfax** [akhilnarang/scripts#108]
Hello,
I ran the android_build_env.sh script and received an "E: Unable to locate package libisl15" error and an "warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build" error in the bootstrapping ninja step. I'm on Ubuntu 19.10. Here's the full log: https://del.dog/android_build_env Thanks for your help.

**Comment by msfjarvis** [comment]
The `libisl15` issue should be resolved on master. `re2c` in Ubuntu is very old and you're better off removing the ninja installation or building and instaling your own.

**Comment by julian-fairfax** [comment]
This fixed the issue. Thanks a lot.
