### ISSUE TITLE
curl doesn't seem to be installed by default on kubuntu 20.04.1 minimal

### ISSUE THREAD

**Issue by Laikar** [akhilnarang/scripts#134]
I ran the script on a fresh install of kubuntu 20.04.1 minimal, and curl doesn't seem to be installed.

**Comment by akhilnarang** [comment]
Can you send the output of `lsb_release -d`

**Comment by Laikar** [comment]
Ubuntu 20.04.1 LTS

https://i.imgur.com/6y88ct3.png
