### ISSUE TITLE
Stop symlinking libncurses5 for Ubuntu 18.04 and 20.04 in setup script

### ISSUE THREAD

**Issue by theimpulson** [akhilnarang/scripts#136]
For both distributions, libncurses5 is available via apt. The preferred method should be to use the apt version if possible in my opinion.

You can check it here:
- https://packages.ubuntu.com/bionic/libncurses5
- https://packages.ubuntu.com/focal/libncurses5

**Comment by akhilnarang** [comment]
Will build on both this weekend to confirm, you can make a PR with the required changes if you want.
