### ISSUE TITLE
Install github cli as well while setting up server

### ISSUE THREAD

**Issue by theimpulson** [akhilnarang/scripts#137]
GitHub has released their own CLI tool. This is useful to upload releases via the terminal after a build is done. Would be cool if you can add support for it in server/android_build_env.sh script.

Ref:
- https://github.com/cli/cli
- https://github.com/cli/cli/blob/trunk/docs/install_linux.md
- https://cli.github.com/manual/gh_release_upload

**Comment by akhilnarang** [comment]
Will see about it.
