### ISSUE TITLE
Fedora script

### ISSUE THREAD

**Issue by TheRingMaster** [akhilnarang/scripts#144]
Works perfectly but noticed on oneplus kernel builds it needs openssl to be installed to pass the certs

**Comment by TheRingMaster** [comment]
Tested on Fedora 33

**Comment by akhilnarang** [comment]
Can you make a PR for it?

**Comment by TheRingMaster** [comment]
yeah i'll work on it

**Comment by TheRingMaster** [comment]
pull request done
