### ISSUE TITLE
Error While Setup

### ISSUE THREAD

**Issue by ifelixculpa** [akhilnarang/scripts#176]
Getting this error while setting up environment

![Screenshot_3](https://user-images.githubusercontent.com/13099434/154860978-a0fef36f-9f80-4522-8853-57c506b73a57.png)

**Comment by gerrydoro** [comment]
Please share the whole log, the script you were using and the distro you are using. Thanks.

**Comment by ifelixculpa** [comment]
> Please share the whole log, the script you were using and the distro you are using. Thanks.

hi i was trying to setup on WSL2 windows 11 using this script

https://github.com/akhilnarang/scripts/blob/master/setup/android_build_env.sh

**Comment by xstefen** [comment]
This isnt for WSL2, and currently requires systemd init which WSL2 does not use
