### ISSUE TITLE
Ubuntu 22.04  404  Not Found [IP: 2606:50c0:8000::153 443] and The repository 'https://cli.github.com/packages jammy Release' does not have a Release file

### ISSUE THREAD

**Issue by METALG0D** [akhilnarang/scripts#181]
Check This
https://github.com/cli/cli/issues/5523#issuecomment-1114720174

( Error )

Ign:2 https://cli.github.com/packages jammy InRelease                                                                                               
Err:3 https://cli.github.com/packages jammy Release                                                                  
  404  Not Found [IP: 2606:50c0:8000::153 443]
Hit:4 http://in.archive.ubuntu.com/ubuntu jammy InRelease                                      
Hit:5 http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease                              
Hit:6 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
E: The repository 'https://cli.github.com/packages jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:1 https://repo.steampowered.com/steam stable InRelease
Ign:2 https://cli.github.com/packages jammy InRelease                                                                                                 
Err:3 https://cli.github.com/packages jammy Release                                                                    
  404  Not Found [IP: 2606:50c0:8000::153 443]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease                                 
Hit:5 http://in.archive.ubuntu.com/ubuntu jammy InRelease     
Hit:6 http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
E: The repository 'https://cli.github.com/packages jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by METALG0D** [comment]
Check this..
https://github.com/cli/cli/issues/5523

**Comment by akhilnarang** [comment]
Do the instructions from [here](https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt) work fine?

**Comment by xstefen** [comment]
#183 should fix
