### ISSUE TITLE
Unifying Ubuntu scripts

### ISSUE THREAD

**Issue by MSF-Jarvis** [akhilnarang/scripts#20]
Using `lsb_release -d` returns the current version running on the system, so in place of two different scripts, we can make just one script that installs all common packages, then detects the current version and installs version specific packages

**Comment by akhilnarang** [comment]
Cool, will check it out soon™, busy now

If possible please test and make a pull request :)

**Comment by MSF-Jarvis** [comment]
Sure, will do, was being lazy™ so even created the issue from the command line. **[hub](https://hub.github.com) for the win**

**Comment by akhilnarang** [comment]
Wow, hub seems great *_*

**Comment by MSF-Jarvis** [comment]
`create` and `fork` are amazing lol

**Comment by DroidThug** [comment]
*____________________*

**Comment by MSF-Jarvis** [comment]
Meh die

**Comment by MSF-Jarvis** [comment]
Okay fine might do it tonight
