### ISSUE TITLE
arch-manjaro.sh: Pacaur isnt there on default repos

### ISSUE THREAD

**Issue by merothh** [akhilnarang/scripts#32]
Line 10
sudo pacman -S pacaur

This won't install pacaur as it isnt available on the default repos and causes the rest of the script to fail for me.

**Comment by akhilnarang** [comment]
You're on Arch or any derivative of arch? I had tested only on manjaro :p 
Will fix soon

**Comment by merothh** [comment]
Arch. Thanks :D
