### ISSUE TITLE
setup/android_build_env.sh on fresh debian install

### ISSUE THREAD

**Issue by yoinx** [akhilnarang/scripts#44]
I am doing a fresh install of Debian 9.4.0. I always use your scripts to setup my build environment, because they're quick, easy and just work.

Anyway, I got this warning toward the end. Not sure if I *need* re2c for a full environment. But, the script doesn't necessarily check that it's installed (it wasn't). I'm installing it manually, so ignore this issue if it is an unimportant warning.

`warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.`

Thanks! Keep up the amazing work.

**Comment by akhilnarang** [comment]
@yoinx yeah it's not needed, it's just used while building ninja to regenerate those files
