### ISSUE TITLE
bash build.sh   File not found

### ISSUE THREAD

**Issue by RobotHanzo** [akhilnarang/scripts#73]
At Ubuntu 18.04, after doing android end setup.sh, I go back to the root dir of the scripts and found typing $bash build.sh gets you nothing, searching build.sh in the whole Ubuntu gets you nothing too, any solutions?

**Comment by RobotHanzo** [comment]
android_build_env.sh **typo

**Comment by akhilnarang** [comment]
Seems unrelated to this, there isn't supposed to be any `build.sh`
